import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/** Repo root: this file sits in `test/`. */
const root = join(import.meta.dirname, '..')
const theme = readFileSync(join(root, 'packages/ui/src/styles/theme.css'), 'utf8')
const tokens = readFileSync(join(root, 'brand/tokens.css'), 'utf8')

/**
 * `theme.css` maps `--lf-*` names out of `brand/tokens.css` into Tailwind's
 * `@theme inline` block, with no fallbacks. `brand/tokens.css` is GENERATED by
 * tooling that lives outside this repository and is copied in.
 *
 * So a token renamed or removed upstream makes `var(--lf-whatever)` invalid at
 * computed-value time, and the property silently resolves to `unset`. Losing
 * `--lf-text` alone leaves the body colour at its initial black -- on a dark
 * surface, in dark mode. No build error, no failing test, no lint (#84).
 *
 * Parsed as TEXT rather than loaded into jsdom, deliberately: jsdom does not
 * resolve custom properties across an imported stylesheet, so a jsdom version
 * of this test would assert against values it never actually computed. The
 * question here is which NAMES exist in which blocks, and that is a question
 * about the files.
 *
 * Lives in `test/` rather than in `packages/ui`, for two reasons that both
 * had to be discovered. `packages/ui`'s tsconfig deliberately excludes Node
 * ambient types (see its own comment), so `node:fs` will not typecheck there.
 * And the Vite-side alternatives do not work either: vitest stubs CSS imports
 * to an empty string by default, so `?raw` and `import.meta.glob(..., {query:
 * '?raw'})` both yield `''` -- measured, not assumed.
 *
 * `test/` is also the more honest home. This asserts an invariant BETWEEN a
 * generated artefact at the repo root and a file in one package; it belongs to
 * neither. `vitest.durability.config.ts` picks up `test/*.test.ts`
 * automatically, and this one needs no stack.
 */
const declared = (body: string): Set<string> =>
  new Set([...body.matchAll(/(--lf-[a-z0-9-]+)\s*:/g)].map((m) => m[1] as string))

/** A top-level block's body, matched to its own closing brace at column 0. */
function block(pattern: string): Set<string> {
  const m = new RegExp(`${pattern}\\s*\\{(.*?)^\\}`, 'sm').exec(tokens)
  if (m == null) throw new Error(`tokens.css has no block matching ${pattern}`)
  return declared(m[1] as string)
}

const referenced = new Set(
  [...theme.matchAll(/var\((--lf-[a-z0-9-]+)/g)].map((m) => m[1] as string),
)
const light = block('^:root')
const mediaDark = block('@media \\(prefers-color-scheme: dark\\)')
const attrDark = block('^:root\\[data-theme="dark"\\]')

describe('brand tokens the theme layer depends on', () => {
  // The guard the issue was filed for: a rename upstream silently unsets the
  // property here.
  it('defines every --lf-* name that theme.css references', () => {
    expect([...referenced].filter((n) => !light.has(n))).toEqual([])
    expect(referenced.size).toBeGreaterThan(0)
  })

  // NOT "defined in both blocks", which is the obvious assertion and is wrong:
  // dark overrides only the 20 tokens whose value changes, and the other 63
  // inherit from `:root` correctly. What must not exist is a token defined
  // ONLY in a dark block -- that one is `unset` in light mode, which is the
  // failure this file's sibling guidance warns about.
  it('has no token defined only in a dark block', () => {
    const darkOnly = [...new Set([...mediaDark, ...attrDark])].filter((n) => !light.has(n))
    expect(darkOnly).toEqual([])
  })

  // The two dark blocks are two routes to the same appearance: the OS
  // preference and the explicit toggle. A name overridden in one and missing
  // from the other means the toggle and the system setting disagree for that
  // property, which is invisible until someone flips one of them.
  it('overrides the same names under the OS preference and the explicit toggle', () => {
    expect([...mediaDark].filter((n) => !attrDark.has(n))).toEqual([])
    expect([...attrDark].filter((n) => !mediaDark.has(n))).toEqual([])
  })
})
